In [1]:
import numpy as np

In [4]:
# 15.2.1 生成一般数组
# 给array()函数传入一个列表
arr1=np.array([2,4,6,8])
arr1

array([2, 4, 6, 8])

In [6]:
# 给array()函数传入一个元组
arr2=np.array((2,4,6,8))
arr2

array([2, 4, 6, 8])

In [7]:
# 给array()函数传入一个嵌套列表
arr3=np.array([[1,2,3],[4,5,6]])
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# 15.2.2 生成特殊类型型数组
# 生成固定范围的随机数组
# 利用arange()函数
np.arange(start,stop,step)
# 以start开始（包括start这个值）
# stop结束（不包括stop这个值）
# step为步长（步长就是数与数之间饿的间隔）

In [8]:
# 生成一个以1为开始，15为结束，3为步长的随机序列
np.arange(1,15,3)

array([ 1,  4,  7, 10, 13])

In [9]:
# 当step参数省略不写时，步长默认为1
# 生成一个以1为开始，15为结束，步长默认的随机序列
np.arange(1,15)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
# 当start参数省略不写时，默认从0开始
# 生成一个以15为结束，步长默认为1的随机序列
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
# 生成指定形状全为0的数组要用到zeros()函数
# 当给zeros()函数传入一个具体的值时，会生成相应长度的一个全为0的一维数组
# 生成长度为3的0数组
np.zeros(3)

array([0., 0., 0.])

In [12]:
# 当给zeros()函数传入一对值时，会生成相应行、列数全为0的多维数组
# 生成2行3列的一个数组
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
# 生成指定形状全为1的数组要用到ones()函数
# 生成长度为3的0数组
np.ones(3)

array([1., 1., 1.])

In [14]:
# 生成2行3列的一个数组
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
# 生成一个正方形单位矩阵
# 单位矩阵就是对角线的元素值全为1，其余位置的元素值全为0，需要用到eye()函数
# eye()函数需要在括号中指明正方形边长

In [17]:
# 生成一个3X3的单位矩阵
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
# 15.2.3 生成随机数组
# 随机数组的生成主要用到NumPy中的random模块
# np.random.rand()方法主要用于生成（0,1)之间的随机数组

In [19]:
# 生成长度为3的位于（0,1)之间的随机数组
# 当给rand()函数传入一个具体的值时，会生成相应长度的且值位于（0，1）之间的随机数组
np.random.rand(3)

array([0.39221651, 0.41788052, 0.89695521])

In [20]:
# 当给rand()函数传入一对值时，会生成相应行、列数的多维数组，且数组中的值介于（0,1）之间
# 生成2行3列的位于（0，1）之间数组
np.random.rand(2,3)

array([[0.04900544, 0.08794961, 0.79115768],
       [0.03123498, 0.64580299, 0.80563797]])

In [21]:
# np.random.randn()方法用来生成满足正态分布的指定形状数组
# 当给rand()函数传入一个具体的值时，会生成一个相应长度的满足正态分布的随机数组
# 生成长度为3的满足正态分布的随机数组
np.random.randn(3)

array([1.08227191, 1.41428887, 0.53657314])

In [22]:
# 当给rand()函数传入一对值时，会生成相应行、列数的多维数组，且数组中的值满足正态分布
# （备注 P253 书中勘误：“满足正太分布”）
# 生成2行3列的位于（0，1）满足正态分布的随机数组
np.random.randn(2,3)

array([[ 0.14636483,  0.48665278,  2.44184169],
       [-0.34423592, -1.21667784, -1.91843834]])

In [ ]:
# np.random.randint()与np.arange()方法类似，用于生成一定范围内的随机数组
# [low,high)表示左闭右开生成数组大小为size的均匀分布的整数值
import numpy as np
np.random.randint(low,high=None,size=None)

In [3]:
# 在区间[1,5)生成长度为10的随机数组
np.random.randint(1,5,10)

array([1, 2, 3, 1, 3, 1, 4, 4, 1, 3])

In [5]:
# 当high参数为空，取值区间就变成[0,low)
# 在区间[0,5)上生成长度为10的随机数组
np.random.randint(5,size=10)

array([3, 1, 4, 2, 2, 0, 0, 3, 3, 3])

In [7]:
# 参数size可以是一个值，生成的随机数组是一维的
# 参数size 也可以是一对值，生成的随机数组就是多维的
# 在区间[0,5)生成2行3列的随机数组
np.random.randint(5,size=(2,3))

array([[2, 0, 2],
       [2, 0, 3]])

In [ ]:
# np.random.choice()方法
# 从已知数组中随机选取相应大小的数组
np.random.choice(a,size=None,replace=None,p=None)
# 从数组a中选取size大小的数组作为一个新的数组
# a 可以是一个数组，也可以是一个整数
# 当a是一个数组时表示从该数组中随机数组
# 当a为整数时，表示从range(int)中采样

In [8]:
# 从数组a中选取3个值组成一个新的数组
np.random.choice(5,3)

array([1, 0, 1])

In [9]:
# 当size是一个具体数值时，生成一维数组
# 当size是一对值时，生成一个指定行列的多维数组
np.random.choice(5,(2,3))

array([[3, 4, 4],
       [2, 2, 2]])

In [10]:
# np.random.shuffle()方法
# np.random.shuffle()方法主要用来将原数组顺序打乱，类似于打扑克牌中的洗牌操作
# 原数组顺序
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# 乱序后的数组
np.random.shuffle(arr)
arr

array([9, 6, 7, 8, 3, 4, 2, 0, 5, 1])