In [1]:
# 15.4.1 一维数据的选取
# 数据选取就是通过索引的方式把想要的某些值从全部数据中抽取出来

In [3]:
# 新建一个一维数组
import numpy as np
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# 传入某个位置
# numpy中的位置从0开始计数
# 获取第4位的数，即传入3
arr[3]

3

In [5]:
# 获取末尾的数值时，直接给数组传入-1，表示获取末尾最后一个数
# 当给数组传入-2时，表示获取末尾第二个值
# 数组正序从0开始数，倒序从-1开始数
# 获取末尾最后一个数值
arr[-1]

9

In [7]:
# 获取末尾倒数第二个数值
arr[-2]

8

In [8]:
# 传入某个位置区间
# 数组中每个元素都有一个位置，如果想要获取某些连续位置的元素，则可以将这些元素对应的位置表示一个区间
# 只要写明元素开始的位置和结束的位置即可
# 位置默认是一个左闭右开区间，即选取开始位置的元素，但不选取结束位置的元素

In [9]:
# 获取位置3到5的值，不包含位置5的值
arr[3:5]

array([3, 4])

In [10]:
# 选取某个位置之后的所有元素，只要指明开始位置即可
# 获取位置3以后的所有元素
arr[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [11]:
# 选取某个位置之前的所有元素，只要指明结束位置即可
# 获取位置3之前的所有元素
arr[:3]

array([0, 1, 2])

In [12]:
# 正序位置和倒序位置可混用
# 获取从第3位到倒数第2位的元素，不包括倒数第2位
arr[3:-2]

array([3, 4, 5, 6, 7])

In [13]:
# 传入某个条件
# 给数组传入某个判断条件，将返回符号该条件的元素
# 获取数组中大于3的元素
arr[arr>3]

array([4, 5, 6, 7, 8, 9])

In [14]:
# 15.4.2 多维数据选取
# 建立一个多维数组供使用
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
# 获取某行数据，直接传入这行的位置，即第几行即可
# 获取第2行数据
arr1[1]

array([4, 5, 6])

In [16]:
# 获取第2行和第3行的数据，包括第3行
arr1[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [17]:
# 获取第3行之前的所有数据，不包括第3行
arr1[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
# 逗号之前用来指明行位置
# 逗号之后用来指明列位置
# 当逗号之前是一个冒号时，表示获取所有的行
# 获取第2列数据
arr1[:,1]

array([2, 5, 8])

In [19]:
# 获取第1到3列的数据，包括第3列
arr1[:,0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [20]:
# 获取第3列之前的所有列，不包括第3列
arr1[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [22]:
# 获取第2列之后的所有列，包括第2列
arr1[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [24]:
# 行列同时获取时，分布在行位置、列位置处指明要获取行、列的位置数
# 获取第1到2行，第2到3列的数据
arr1[0:2,1:3]

array([[2, 3],
       [5, 6]])