In [1]:
# 15.5.1 Numpy数组的类型转换
# 在numpy数组中转换数据类型用到的方法是astyle()，在括号中指明要转换成的目标类型即可

In [2]:
import numpy as np

In [4]:
arr=np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [5]:
# 数组arr的原数据类型为int32
arr.dtype

dtype('int64')

In [6]:
# 将arr数组从int类型转换为float类型
arr_float=arr.astype(np.float64)
arr_float

array([0., 1., 2., 3., 4.])

In [7]:
arr_float.dtype

dtype('float64')

In [8]:
# 将arr数组从int类型转换为str类型
arr_str=arr.astype(np.string_)
arr_str

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S21')

In [9]:
arr_str.dtype

dtype('S21')

In [10]:
# 15.5.2 NumPy数组的缺失值处理
# 分为两步：第一步先判断是否含有缺失值，第二部对缺失值进行填充

In [11]:
# 查找缺失值用到的方法是isnan()
# 在判断缺失值前，先创建一个含有缺失值的数组，在numpy中缺失值用np.nan表示
# 创建一个含有缺失值的数组，nan表示缺失值
arr1=np.array([1,2,np.nan,4])
arr1

array([ 1.,  2., nan,  4.])

In [12]:
# 如果某一位置的值为缺失值，则该位置返回True，否则返回False
# 第三位为缺失值
np.isnan(arr1)

array([False, False,  True, False])

In [14]:
# 找到缺失值以后填充0
arr1[np.isnan(arr1)]=0
arr1

array([1., 2., 0., 4.])

In [15]:
# 15.5.3 NumPy数组的重复值处理
# 直接调用unique()方法
arr2=np.array([1,2,3,2,1])
np.unique(arr2)

array([1, 2, 3])