In [1]:
# 所谓数组重塑就是更改数组的形状，比如原来3行4列的数组重塑成4行3列的数组
# 在numpy中用reshape方法来实现数组重塑

In [2]:
# 15.6.1 一维数组重塑
# 一维数组重塑就是将数组从一行或一列数组重塑为多行多列的数组

In [3]:
# 新建一个一维数组
import numpy as np
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [4]:
# 将数组重塑为2行4列的多维数组
arr.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [5]:
# 将数组重塑为4行2列的多维数组
arr.reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [6]:
# 不管是重塑为2行4列还是4行2列，只要重塑后数组中值的个数等于一维数组中 的值的个数即可

In [7]:
# 15.6.2 多维数组重塑
# 新建一个多维数组
arr1= np.array([[1, 2, 3,4],
       [5, 6,7,8],
       [9,10,11,12]])
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
# 将数组重塑为4行3列
arr1.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [10]:
# 将数组重塑为2行6列
arr1.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [11]:
# 不管是重塑为3行4列还是2行6列，只要重塑后数组中值的个数等于重塑前数组中的值的个数即可

In [13]:
# 15.6.3 数组转置
# 数组转置就是将数组的行旋转为列，用到的方法是.T

In [14]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
arr1.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])