In [1]:
# 15.7.1 横向合并
# numpy数组合并并不需要公共列，只是将两个数组简单拼接在一起，有concatenate、hstack、column_stack三种方法

In [4]:
# 先新建两个数组，再进行合并
import numpy as np
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])

In [5]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [7]:
# concatenate方法
# 将两个待合并的数组以列表的形式传给concatenate，并通过axis参数来指明在行方向和列方向上进行合并
np.concatenate([arr1,arr2],axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [8]:
# 参数axis=1表示数组在行方向上进行合并

In [9]:
# hstack方法
# 直接将两个待合并数组以元组的形式传给hstack即可，不需要设置axis参数
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [10]:
# column_stack方法
# 直接将两个待合并数组以元组的形式传给column_stack即可
np.column_stack((arr1,arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [11]:
# 15.7.2 纵向合并
# 将两个列数相等的数组在列的方向进行拼接，有concatenate、vstack、row_stack三种方法

In [12]:
# concatenate方法
# 使用concatenate方法对数组进行纵向合并，参数axis的值必须为0
np.concatenate([arr1,arr2],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [13]:
# vstack方法
# 直接将两个待合并数组以元组的形式传给vstack即可，不需要设置axis参数
np.vstack((arr1,arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [14]:
# row_stack方法
# 直接将两个待合并数组以元组的形式传给row_stack即可
np.row_stack((arr1,arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])