In [1]:
# 15.8.1 元素级函数
# 主要函数及其说明

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.DataFrame([['abs','求取每个元素的绝对值'],
                   ['sqrt','求取每个元素的平方根'],
                   ['square','求取每个元素的平方'],
                   ['exp','求取每个元素的以e为底的指数'],
                   ['log、log10、log2、log1p','分布计算以e为底、10为底、2为底的对数，以及log(1+x)'],
                   ['modf','适用于浮点数，将小数和整数部分以独立的数组返回'],
                   ['isnan','用来判断是否是NaN，返回一个布尔值']],
                 columns=('函数','说明'))
df

函数                               说明
0                   abs                       求取每个元素的绝对值
1                  sqrt                       求取每个元素的平方根
2                square                        求取每个元素的平方
3                   exp                   求取每个元素的以e为底的指数
4  log、log10、log2、log1p  分布计算以e为底、10为底、2为底的对数，以及log(1+x)
5                  modf          适用于浮点数，将小数和整数部分以独立的数组返回
6                 isnan               用来判断是否是NaN，返回一个布尔值

In [7]:
# 元素级函数的用法
# 新建一个数组
import numpy as np
arr =np.arange(4)
arr

array([0, 1, 2, 3])

In [8]:
# 求取各个元素的平方
np.square(arr)

array([0, 1, 4, 9])

In [9]:
# 求取各个元素的平方根
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081])

In [10]:
# 15.8.2 描述统计函数
# 主要的函数及其说明
df2 = pd.DataFrame([['sum','对数组中全部元素或某行/列的元素求和'],
                    ['mean','平均值求取'],
                    ['std、var','分别为标准差和方差'],
                    ['min、max','分别为最小值和最大值'],
                    ['argmin、argmax','分别为最小值和最大值对应的索引'],
                    ['cumsum','所有元素的累计和，结果以数组的形式返回'],
                    ['cumprod','所有元素的累计积']],
                  columns=('函数','说明'))
df2

函数                   说明
0            sum   对数组中全部元素或某行/列的元素求和
1           mean                平均值求取
2        std、var            分别为标准差和方差
3        min、max           分别为最小值和最大值
4  argmin、argmax      分别为最小值和最大值对应的索引
5         cumsum  所有元素的累计和，结果以数组的形式返回
6        cumprod             所有元素的累计积

In [11]:
# 新建一个数组
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
# 求和
# 对整个数组进行求和
arr1.sum()

45

In [13]:
# 对数组中的每一行分别求和
arr1.sum(axis=1)

array([ 6, 15, 24])

In [14]:
# 对数组中的每一列分别求和
arr1.sum(axis=0)

array([12, 15, 18])

In [15]:
# 对整个数组进行平均值
arr1.mean()

5.0

In [16]:
# 对数组中的每一行分别求均值
arr1.mean(axis=1)

array([2., 5., 8.])

In [17]:
# 对数组中的每一列分别求均值
arr1.mean(axis=0)

array([4., 5., 6.])

In [18]:
# 求最值
# 对整个数组求最大值
arr1.max()

9

In [20]:
# 对数组中的每一行分别求最小值
arr1.min(axis=1)

array([1, 4, 7])

In [21]:
# 对数组中的每一列分别求最大值
arr1.max(axis=0)

array([7, 8, 9])

In [22]:
# 15.8.3 条件函数
# Numpy数组中的条件函数np.where(condition,x,y)类似于Excel中的if(condition,True,False)函数
# 如果条件（condition)为真则返回x,如果条件为假则返回y
# 新建一个数组用来存储学生成绩
arr2 =np.array([56,61,65])
arr2

array([56, 61, 65])

In [23]:
# 大于50及格，小于60不及格
np.where(arr2>60,'及格','不及格')

array(['不及格', '及格', '及格'], dtype='<U3')

In [24]:
# 返回满足条件的值对应的位置
np.where(arr2>60)

(array([1, 2]),)

In [25]:
# 15.8.4 集合关系
# 集合主要有包含、交集、并集、差集

In [26]:
# 新建两个数组
arr3=np.array([1,2,3,4])
arr4=np.array([1,2,5])

In [28]:
# 包含
np.in1d(arr3,arr4)

array([ True,  True, False, False])

In [29]:
# 交集
np.intersect1d(arr3,arr4)

array([1, 2])

In [30]:
# 并集
np.union1d(arr3,arr4)

array([1, 2, 3, 4, 5])

In [31]:
# 差集
np.setdiff1d(arr3,arr4)

array([3, 4])